### ISSUE TITLE
solutie alimentare

### ISSUE THREAD

**Issue by agmuntianu** [andreihritac/3lvl-greenhouse#5]

**Comment by andreihritac** [comment]
![img_20161219_172240](https://cloud.githubusercontent.com/assets/10183275/21318206/e56541c8-c610-11e6-993c-42f095acf44e.jpg)
![img_20161219_172216](https://cloud.githubusercontent.com/assets/10183275/21318207/e58e0914-c610-11e6-9253-443863ad02da.jpg)

Converted PC PSU for temporary power supply
